apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cnbc-homelab
servers: 1
agents: 2
kubeAPI:
  host: "0.0.0.0"
  hostIP: "0.0.0.0"
  hostPort: "8545"
image: rancher/k3s:v1.29.2-k3s1
network: cnbc-homelab
registries:
  config: |
    mirrors:
      docker.io:
        endpoint:
        - "http://host.docker.internal:5001"
      k8s.io:
        endpoint:
        - "http://host.docker.internal:5002"
      cnbc-registry:
        endpoint:
        - "http://host.docker.internal:5003"
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: true
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
      - settings.workerConnections=2048
  k3s:
    extraArgs:
    - arg: --disable=servicelb
      nodeFilters:
      - server:*
    - arg: --disable=traefik
      nodeFilters:
      - server:*
    - arg: --disable-network-policy
      nodeFilters:
      - server:*
    - arg: --disable-kube-proxy
      nodeFilters:
      - server:*
    - arg: --flannel-backend=none
      nodeFilters:
      - server:*
    - arg: --cluster-init=true
      nodeFilters:
      - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    ulimits:
    - name: nofile
      soft: 26677
      hard: 26677
