apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: cnbc-homelab
servers: 1
agents: 2
kubeAPI:
  host: "cnbc-homelab.bee42.io"
  hostIP: "0.0.0.0"
  hostPort: "8545"
image: rancher/k3s:v1.29.1-k3s2
network: cnbc-homelab
subnet: "172.28.0.0/16"
token: cnbc-DEV-0815!
#volumes:
#- volume: /Users/peter/develop/brewup/add-on/kubernetes/k3d/manifests:/var/lib/rancher/k3s/server/manifests
#  nodeFilters:
#  - server:0
registries:
  #  create: # creates a default registry to be used with the cluster; same as `--registry-create registry.localhost`
  #    name: registry.localhost
  #   host: "0.0.0.0"
  #    hostPort: "5000"
  #use:
  #- host.docker.internal:5003
  config: |
    mirrors:
      docker.io:
        endpoint:
        - "http://host.docker.internal:5001"
      k8s.io:
        endpoint:
        - "http://host.docker.internal:5002"
      cnbc-registry:
        endpoint:
        - "http://host.docker.internal:5003"
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: true
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
      - settings.workerConnections=2048
  k3s:
    extraArgs:
    - arg: --tls-san=cnbc-homelab.bee42.io
      nodeFilters:
      - server:*
    - arg: --disable=traefik
      nodeFilters:
      - server:*
    - arg: --disable-network-policy
      nodeFilters:
      - server:*
    - arg: --disable-kube-proxy
      nodeFilters:
      - server:*
    nodeLabels:
    - label: node-role.kubernetes.io/worker=true
      nodeFilters:
      - agent:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    gpuRequest: all
    ulimits:
    - name: nofile
      soft: 26677
      hard: 26677
