# ----
# File:        cnbc-homelab.yaml
# Description: k3d clusters configuration to enable cilium CNI network provider
# Author:      Peter Rossbach <peter.rossbach@bee42.com>
# Copyright:   (c) 2024 bee42 solutions gmbh
# ----
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cnbc-homelab
servers: 1
agents: 2
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
image: docker.io/rancher/k3s:v1.29.2-k3s1
network: cnbc-homelab
volumes:
- volume: /Users/peter/develop/brewup/add-on/kubernetes/k3d/bin/k3d-entrypoint-cilium.sh:/bin/k3d-entrypoint-cilium.sh
  nodeFilters:
  - all
registries:
  config: |
    mirrors:
      docker.io:
        endpoint:
        - "http://host.docker.internal:5001"
      k8s.io:
        endpoint:
        - "http://host.docker.internal:5002"
      "cnbc-registry:5003":
        endpoint:
        - "http://host.docker.internal:5003"
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: true
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
      - settings.workerConnections=2048
  k3s:
    extraArgs:
    - arg: --disable-cloud-controller
      nodeFilters:
      - server:*
    - arg: --disable=servicelb
      nodeFilters:
      - server:*
    - arg: --disable=traefik
      nodeFilters:
      - server:*
    - arg: --disable-network-policy
      nodeFilters:
      - server:*
    - arg: --disable-kube-proxy
      nodeFilters:
      - server:*
    - arg: --flannel-backend=none
      nodeFilters:
      - server:*
      #    - arg: --cluster-init
      #      nodeFilters:
      #      - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    ulimits:
    - name: nofile
      soft: 26677
      hard: 26677
    labels:
    - label: role.kubernetes.io/worker=worker
      nodeFilters:
      - agent:*
