version: '3.7'
services:
  docker-mirror:
    image: registry:2
    ports:
      - 5001:5001
    environment:
      - TZ=Europe/Berlin
    volumes:
      - docker-mirror:/var/lib/registry
      - ./docker-mirror.yml:/etc/docker/registry/config.yml
    restart: always
  k8s-mirror:
    image: registry:2
    ports:
      - 5002:5002
    environment:
      - TZ=Europe/Berlin
    volumes:
      - k8s-mirror:/var/lib/registry
      - ./k8s-mirror.yml:/etc/docker/registry/config.yml
    restart: always

  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Berlin
    volumes:
      - registry:/var/lib/registry
      - ./registry.yml:/etc/docker/registry/config.yml
    restart: always
  git:
    image: rockstorm/git-server:2.43
    ports:
      - 2222:22
    environment:
      - TZ=Europe/Berlin
      - GIT_PASSWORD=12345
      - SSH_AUTH_METHODS=publickey password
    volumes:
      - git-server:/srv/git
      - ./ssh:/home/git/.ssh
    restart: always

volumes:
  registry: {}
  k8s-mirror: {}
  docker-mirror: {}
  git-server: {}
