apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: cilium
  namespace: kube-system
spec:
  valuesContent: |
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    bpf:
      masquerade: true
    bgp:
      enabled: false
    cluster:
      name: cnbc-homelab
      id: 2
    endpointRoutes:
      enabled: true
    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: true
      # https://github.com/cilium/cilium/issues/26586
      leaseDuration: 120s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 1s
    loadBalancer:
      algorithm: maglev
      mode: snat
    localRedirectPolicy: true
    ingressController:
      enabled: true
      loadbalancerMode: "shared"
    k8sServiceHost: "172.28.0.2"
    k8sServicePort: 6443
    ipv4NativeRoutingCIDR: "172.28.0.0/16"
