apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: external-dns
  namespace: kube-system
spec:
  valuesContent: |-
    provider: coredns
    coredns:
      etcdEndpoints: http://etcd.coredns.svc.cluster.local:2379

    logLevel: debug
    domainFilters:
    - cnbc-dev.bee42.io
    txtOwnerId: cnbc-dev
    txtPrefix: cnbc-dev-

    crd:
      create: true
      apiversion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint

    metrics:
      enabled: false
      serviceMonitor:
        enabled: true
        labels:
          prometheus: central

    sources:
    - crd
    - service
    - ingress
    - traefik-proxy
