# ----
# File:        values-cilium.yaml
# Description: Helm Chart Cilium CNI network provider configuration
# Author:      Peter Rossbach <peter.rossbach@bee42.com>
# Copyright:   (c) 2024 bee42 solutions gmbh
# ----
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
bpf:
  masquerade: true
bgp:
  enabled: false
cluster:
  name: cnbc-homelab
  id: 3
endpointRoutes:
  enabled: true
ipam:
  mode: kubernetes
k8s:
  requireIPv4PodCIDR: true
kubeProxyReplacement: strict
#kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
  # https://github.com/cilium/cilium/issues/26586
  leaseDuration: 120s
  leaseRenewDeadline: 60s
  leaseRetryPeriod: 1s
loadBalancer:
  algorithm: maglev
  mode: snat
localRedirectPolicy: true
ingressController:
  enabled: true
  loadbalancerMode: "shared"
hostServices:
  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
debug:
  # -- Enable debug logging
  enabled: true
  # -- Configure verbosity levels for debug logging
  # This option is used to enable debug messages for operations related to such
  # sub-system such as (e.g. kvstore, envoy, datapath or policy), and flow is
  # for enabling debug messages emitted per request, message and connection.
  # Multiple values can be set via a space-separated string (e.g. "datapath envoy").
  #
  # Applicable values:
  # - flow
  # - kvstore
  # - envoy
  # - datapath
  # - policy
  verbose: envoy
envoy:
  enabled: true
