apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: coredns
  namespace: coredns
spec:
  repo: https://coredns.github.io/helm
  chart: coredns
  version: "1.29.0"
  createNamespace: true
  targetNamespace: coredns
